language: go
os:
  - windows
  - linux
  - osx
go:
  - "1.12"
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
install:
  - go mod download
  - go get github.com/rakyll/gotest
script:
  - CI=travis
  - gotest -race -v ./... -tags integration -coverpkg=./... -covermode=atomic -coverprofile=coverage.out
after_success:
  - CI=true
  - bash <(curl -s https://codecov.io/bash)
